/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        navy: {
          50: '#f5f7fb',
          100: '#e9ecf4',
          200: '#cfd7e5',
          300: '#a8b5ca',
          400: '#7485a2',
          500: '#4e5f7b',
          600: '#33465d',
          700: '#243445',
          800: '#1a2735',
          900: '#0f1723',
        },
        linen: {
          50: '#fcfaf6',
          100: '#f5efe5',
          200: '#eadfcf',
          300: '#d9c8a9',
          400: '#c7af80',
          500: '#b5914f',
          600: '#9a763d',
          700: '#74542c',
          800: '#4f3b1f',
          900: '#2c2413',
        },
        gold: {
          50: '#fff9e8',
          100: '#fff0c0',
          200: '#ffe28e',
          300: '#ffd35a',
          400: '#f8c53d',
          500: '#e0a91c',
          600: '#b47b0f',
          700: '#83550a',
          800: '#55390a',
          900: '#2f2206',
        },
        danger: '#ef4444',
      },
      fontFamily: {
        sans: ['var(--font-noto)', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        'pulse-ring': {
          '0%,100%': { boxShadow: '0 0 0 0 rgba(16,185,129,0.4)' },
          '50%':      { boxShadow: '0 0 0 10px rgba(16,185,129,0)' },
        },
        'pulse-ring-sky': {
          '0%,100%': { boxShadow: '0 0 0 0 rgba(14,165,233,0.4)' },
          '50%':      { boxShadow: '0 0 0 10px rgba(14,165,233,0)' },
        },
        'slide-up': {
          '0%':   { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%':   { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'pulse-ring':     'pulse-ring 2s ease-in-out infinite',
        'pulse-ring-sky': 'pulse-ring-sky 2s ease-in-out infinite',
        'slide-up':       'slide-up 0.25s ease-out',
        'scale-in':       'scale-in 0.2s ease-out',
      },
    },
  },
  plugins: [],
}
